Allow build of negotiate auth helpers.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -3,7 +3,7 @@ dnl  Configuration input file for Squid
 dnl
 dnl  Duane Wessels, wessels@nlanr.net, February 1996 (autoconf v2.9)
 dnl
-dnl  $Id: configure.in,v 1.320 2006/05/21 09:40:30 serassio Exp $
+dnl  $Id: configure.in,v 1.321 2006/05/21 14:19:30 serassio Exp $
 dnl
 dnl
 dnl
@@ -11,7 +11,7 @@ AC_INIT(src/main.c)
 AC_CONFIG_AUX_DIR(cfgaux)
 AM_INIT_AUTOMAKE(squid, 2.6.DEVEL-CVS)
 AM_CONFIG_HEADER(include/autoconf.h)
-AC_REVISION($Revision: 1.320 $)dnl
+AC_REVISION($Revision: 1.321 $)dnl
 AC_PREFIX_DEFAULT(/usr/local/squid)
 AM_MAINTAINER_MODE
 
@@ -1189,6 +1189,41 @@ if test -n "$DIGEST_AUTH_HELPERS"; then
     echo "Digest auth helpers built: $DIGEST_AUTH_HELPERS"
 fi
 AC_SUBST(DIGEST_AUTH_HELPERS)
+
+dnl Select negotiate auth scheme helpers to build
+NEGOTIATE_AUTH_HELPERS=
+AC_ARG_ENABLE(negotiate-auth-helpers,
+[  --enable-negotiate-auth-helpers=\"list of helpers\"
+                          This option selects which negotiate scheme authentication
+                          helpers to build and install as part of the normal build
+                          process. For a list of available helpers see the
+                          helpers/negotiate_auth directory.],
+[ case "$enableval" in
+  yes)
+    for helper in $srcdir/helpers/negotiate_auth/*; do
+        if test -f $helper/Makefile.in; then
+            NEGOTIATE_AUTH_HELPERS="$NEGOTIATE_AUTH_HELPERS `basename $helper`"
+        fi
+    done
+    ;;
+  no)
+    ;;
+  *)
+    NEGOTIATE_AUTH_HELPERS="`echo $enableval| sed -e 's/,/ /g;s/  */ /g'`"
+  esac
+])
+if test -n "$NEGOTIATE_AUTH_HELPERS"; then
+    for helper in $NEGOTIATE_AUTH_HELPERS; do
+	if test -f $srcdir/helpers/negotiate_auth/$helper/Makefile.in; then
+		:
+	else
+		echo "ERROR: negotiate auth helper $helper does not exists"
+		exit 1
+	fi
+    done
+    echo "Negotiate auth helpers built: $NEGOTIATE_AUTH_HELPERS"
+fi
+AC_SUBST(NEGOTIATE_AUTH_HELPERS)
 
 dnl Enable "NTLM fail open"
 AC_ARG_ENABLE(ntlm-fail-open,
