Added a small trap detecting incorrect --with-aufs-threads arguments

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -3,7 +3,7 @@ dnl  Configuration input file for Squid
 dnl
 dnl  Duane Wessels, wessels@nlanr.net, February 1996 (autoconf v2.9)
 dnl
-dnl  $Id: configure.in,v 1.298 2003/01/18 01:59:52 hno Exp $
+dnl  $Id: configure.in,v 1.299 2003/02/05 06:44:36 hno Exp $
 dnl
 dnl
 dnl
@@ -13,7 +13,7 @@ AC_CONFIG_SRCDIR([src/main.c])
 AC_CONFIG_AUX_DIR(cfgaux)
 AM_INIT_AUTOMAKE(squid, 2.6-DEVEL)
 AM_CONFIG_HEADER(include/autoconf.h)
-AC_REVISION($Revision: 1.298 $)dnl
+AC_REVISION($Revision: 1.299 $)dnl
 AC_PREFIX_DEFAULT(/usr/local/squid)
 AM_MAINTAINER_MODE
 
@@ -300,7 +300,16 @@ AC_ARG_WITH(aufs-threads,
 [  --with-aufs-threads=N_THREADS
                           Tune the number of worker threads for the aufs object
                           store.],
-[ aufs_io_threads=$withval ])
+[ case $withval in
+  [[0-9]]*)
+    aufs_io_threads=$withval
+    ;;
+  *)
+    echo "ERROR: Invalid --with-aufs-threads argument"
+    exit 1
+    ;;
+  esac
+])
 if test "$aufs_io_threads"; then
     echo "With $aufs_io_threads aufs threads"
     AC_DEFINE_UNQUOTED(AUFS_IO_THREADS,$aufs_io_threads,
